development: &global_settings
  database: echorbac_development
  host: 127.0.0.1
  port: 27017

test:
  database: echorbac_test
  <<: *global_settings

production:
  host: hostname
  database: echorbac_production
  username: username
  password: password
  <<: *global_settings