development:
	server: localhost
	database: preallowed_development
	
test:
    server: localhost
    database: preallowed_test
    
production:
    server: localhost
    database: preallowed_production
    